name: myapp
description: A Flutter project

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  flutter_svg: ^0.22.0
  cloud_firestore: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/material-symbols-arrow-forward-ios-rounded.png
    - assets/page-1/images/ph-dot-bold.png
    - assets/page-1/images/material-symbols-arrow-back-ios-rounded.png
    - assets/page-1/images/material-symbols-arrow-back-ios-rounded-fCM.png
    - assets/page-1/images/fluent-mdl2-circle-addition.png
    - assets/page-1/images/group-1.png
    - assets/page-1/images/material-symbols-calendar-month.png
    - assets/page-1/images/material-symbols-calendar-month-sYm.png
    - assets/page-1/images/material-symbols-arrow-back-ios-rounded-5Vj.png
    - assets/page-1/images/group-1-B6R.png
    - assets/page-1/images/material-symbols-arrow-back-ios-rounded-hRT.png
    - assets/page-1/images/mdi-close.png
    - assets/page-1/images/mdi-close-1PP.png
    - assets/page-1/images/ph-dot-bold-KaR.png
    - assets/page-1/images/google.png
    - assets/page-1/images/mdi-close-P93.png
    - assets/page-1/images/mdi-close-rG1.png
    - assets/page-1/images/ellipse-1-5mb.png
