// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlAilGIzySZzxdUKJvUT0MzjsCpIBO4N4',
    appId: '1:334583198681:web:e24a9f9479daf13cf01fc8',
    messagingSenderId: '334583198681',
    projectId: 'login-f4940',
    authDomain: 'login-f4940.firebaseapp.com',
    storageBucket: 'login-f4940.appspot.com',
    measurementId: 'G-QZZGB4GRQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5XR0l1Ym6E-AGl8F68NVRX3f4vPwempM',
    appId: '1:334583198681:android:c1d554e6abca61a8f01fc8',
    messagingSenderId: '334583198681',
    projectId: 'login-f4940',
    storageBucket: 'login-f4940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOt5af8jPqUH7UWKdcY-71zXyd13IT10U',
    appId: '1:334583198681:ios:ec8602789653df27f01fc8',
    messagingSenderId: '334583198681',
    projectId: 'login-f4940',
    storageBucket: 'login-f4940.appspot.com',
    androidClientId: '334583198681-7h10lgpmbvmt276mfgnmq3989ib6ij5c.apps.googleusercontent.com',
    iosClientId: '334583198681-4dqod5itfa124974srtpgrjdmq5r1n11.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOt5af8jPqUH7UWKdcY-71zXyd13IT10U',
    appId: '1:334583198681:ios:ec8602789653df27f01fc8',
    messagingSenderId: '334583198681',
    projectId: 'login-f4940',
    storageBucket: 'login-f4940.appspot.com',
    androidClientId: '334583198681-7h10lgpmbvmt276mfgnmq3989ib6ij5c.apps.googleusercontent.com',
    iosClientId: '334583198681-4dqod5itfa124974srtpgrjdmq5r1n11.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
